### PR TITLE
Feat: Included all car datas in a JSON file

### PR DESCRIPTION
**Pull request by yhoungdev**
* Fixed Jquery issue in script.json
* Fixed undefined button in script.js
* Get all car datas from cars.json into script.js

### CODE REVIEW

**Comment by yhoungdev** [comment]
This PR fixes the issu in #13

**Comment by Alok5102R** [comment]
Okay @yhoungdev .
i'm checking it

**Review by Alok5102R — CHANGES_REQUESTED** [review]
@yhoungdev It's fetching data also btn that you'd used in "script.js" has no use.
Please avoid creation of different folders, put all in "page" folder. Don't give VS code data.

**Comment by Alok5102R** [comment]
Since, there is no response from your side. I need to close this @yhoungdev .

**Pull request closed without merging**
