### PR TITLE
adding tesla models to the json file

### LINKED ISSUE #57: adding tesla cars to the json
to support the climate change forum i have decided to add the tesla models to the JSON file

### PR DESCRIPTION
**Pull request by kasuba97**
close #57

### CODE REVIEW

**Review by Alok5102R — CHANGES_REQUESTED** [review]
@kasuba97 update their prices correctly and all their available colours.

**Comment by kasuba97** [comment]
Okay 
just that I dont know how much 1 lac equals to converted to usd

care to share?

**Comment by Alok5102R** [comment]
@kasuba97 

1$ = Rs. 82

Use this conversion

**Review by Alok5102R — APPROVED** [review]
Perfect @kasuba97

**Comment by Alok5102R** [comment]
Thanks for your contribution. ❤️
Do [Follow](https://github.com/Alok5102R) 👤 and Star this repository [whichcar](https://github.com/Alok5102R/whichcar) ⭐.

**Pull request merged**
