### PR TITLE
check this and give feedback

### PR DESCRIPTION
**Pull request by kasuba97**
trying to improve the lander

### CODE REVIEW

**Comment by kasuba97** [comment]
https://kasuba97.github.io/whichcar/ 

check on this link

**Comment by Alok5102R** [comment]
It's not responsive @kasuba97

**Comment by kasuba97** [comment]
will need to work on that

**Comment by Alok5102R** [comment]
Yes @kasuba97

**Comment by Alok5102R** [comment]
are you working on it @kasuba97 ?

**Pull request closed without merging**
