### PR TITLE
Making navbar sticky

### LINKED ISSUE #33: modifying navbar
Make the navbar sticky . Kindly assign me this issue

### PR DESCRIPTION
**Pull request by Gopal2021025**
# FIXES #33  
Made the navbar stick to top and also made the logo redirecting. @Alok5102R kindly check the PR
sticky

### CODE REVIEW

**Comment by Alok5102R** [comment]
@Gopal2021025 perform the same on "choose.html" also

**Comment by Gopal2021025** [comment]
@Alok5102R I have made the required changes . Kindly check the PR now.

**Comment by Alok5102R** [comment]
Perfect @Gopal2021025

**Review by Alok5102R — COMMENTED** [review]
Thanks!!

**Pull request merged**
