### PR TITLE
Added a dynamic logo with Animation

### PR DESCRIPTION
**Pull request by SSHSRN**
Signed-off-by: SRIHARI S <sshsrn@gmail.com>

### CODE REVIEW

**Comment by SSHSRN** [comment]
https://user-images.githubusercontent.com/62781914/197388949-8a5df1c8-e963-404c-929b-b58768368413.mp4


I am attaching a screen recording for your reference.

**Comment by SSHSRN** [comment]
@Alok5102R Kindly check!

**Review by Alok5102R — APPROVED** [review]
Perfect @SSHSRN

**Comment by Alok5102R** [comment]
Thanks for your contribution. ❤️
Do [Follow](https://github.com/Alok5102R) 👤 and Star this repository [whichcar](https://github.com/Alok5102R/whichcar) ⭐.

**Pull request merged**
