### PR TITLE
Fixed issue and created new style.css file

### PR DESCRIPTION
**Pull request by SukarayamJanjua**
I've improved the negative values issue
improved some hovering effect on logo
added default values to input fields
and some little bit improvements here and there
Happy hactoberfest-2022 😊✌

### CODE REVIEW

**Comment by Alok5102R** [comment]
@SukarayamJanjua A CSS file already exists in the project. Update your code in that and avoid creation of multiple files.

**Comment by SukarayamJanjua** [comment]
Well...did that ✌..updated my css code in existing app.css and deleted the new style.css

**Review by Alok5102R — CHANGES_REQUESTED** [review]
Sorry wrong issue was written previously.
Issue with your code is:
When you set default values in choose.html it's creating issues and not showing results.
To fix this you need to update script file also.

**Comment by SukarayamJanjua** [comment]
@Alok5102R Well ...how come ? I didn't interfere with home page animation.Indeed its working just perfect on my pc !!

**Comment by SukarayamJanjua** [comment]
@Alok5102R Have a look now

**Comment by Alok5102R** [comment]
@SukarayamJanjua 
Sorry wrong issue was written previously.
Issue with your code is:
When you set default values in choose.html it's creating issues and not showing results.
To fix this you need to update script file also.

Also, please try to resolve conflicts by making changes in latest commits.

**Comment by Alok5102R** [comment]
Thanks for your time @SukarayamJanjua 
Since, you didn't responded I need to close this.
But, you can contribute in other issues.

**Pull request closed without merging**
