### PR TITLE
effected the auto sliding of cars in homepage

### PR DESCRIPTION
**Pull request by ELIJAHJOHNNY**
I have finished working on making all three car images in the homepage slide automatically. Expecting your review. Thank you

### CODE REVIEW

**Comment by ELIJAHJOHNNY** [comment]
@Alok5102R kindly review. Thank you

**Comment by Alok5102R** [comment]
Ya I'm checking @ELIJAHJOHNNY

**Review by Alok5102R — CHANGES_REQUESTED** [review]
It's perfect.

**Review by Alok5102R — APPROVED** [review]

**Comment by Alok5102R** [comment]
Thanks for your contribution @ELIJAHJOHNNY

**Comment by ELIJAHJOHNNY** [comment]
Rather, I’m grateful I could contribute 🙂…. But please @Alok5102R  my name isn’t added to the contributors list yet

**Comment by Alok5102R** [comment]
Have a look at [Readme.md](https://github.com/Alok5102R/whichcar/blob/main/Readme.md) @ELIJAHJOHNNY

**Review by Alok5102R — COMMENTED** [review]
Thanks!!

**Pull request merged**
