### PR TITLE
Added Light Mode toggle button and Removed whichcar button  

### PR DESCRIPTION
**Pull request by Siddhesh172004**
When user clicks on Logo the user will automatically redirect to the home page so I  have replaced the whichcar button and added the Light mode toggle button. I have forked all the  changes and then  added my changes. I have commented where my code starts and ends to increase readability.  
image

### CODE REVIEW

**Comment by Alok5102R** [comment]
Attach screenshot regarding the same @Siddhesh172004

**Comment by Siddhesh172004** [comment]
image
image


Choose car html page
image

**Comment by Alok5102R** [comment]
@Siddhesh172004 your work is great.
But, please fix merge conflicts.
Always update to get latest commits and avoid conflicts.

**Comment by Siddhesh172004** [comment]
> @Siddhesh172004 your work is great. But, please fix merge conflicts. Always update to get latest commits and avoid conflicts.

Okay

**Comment by Alok5102R** [comment]
Are you working on it @Siddhesh172004

**Comment by Alok5102R** [comment]
Since, there's no response from your side @Siddhesh172004 
I need to close this

**Comment by Siddhesh172004** [comment]
> Since, there's no response from your side @Siddhesh172004 I need to close this

I was little busy. I can fix the issue if you open the issue again.

**Comment by Siddhesh172004** [comment]
> Since, there's no response from your side @Siddhesh172004 I need to close this

I was little busy. I can fix the issue if you open the issue again.

**Comment by Alok5102R** [comment]
Sure @Siddhesh172004 
Please do it a bit fast.
As other issues are pending

**Comment by Siddhesh172004** [comment]
> Sure @Siddhesh172004 Please do it a bit fast. As other issues are pending

okay

**Pull request closed without merging**
