### PR TITLE
Fixed refresh bug

### PR DESCRIPTION
**Pull request by SSHSRN**
Signed-off-by: SRIHARI S <sshsrn@gmail.com>

### CODE REVIEW

**Comment by SSHSRN** [comment]
fixes #53

**Comment by SSHSRN** [comment]
@Alok5102R Kindly check!

**Comment by Alok5102R** [comment]
@SSHSRN attach screen shot regarding this issue

**Comment by SSHSRN** [comment]
https://user-images.githubusercontent.com/62781914/197385112-1aed67c8-b374-4de3-b440-d68b2da05c88.mp4

**Review by Alok5102R — APPROVED** [review]
Cool

**Pull request merged**
